version: '3.1'

services:

  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./static/:/code/static/
      - ./media/:/code/media/
    depends_on:
      - web

  db:
    image: postgres:latest
    env_file:
        - .env
    restart: always
    ports: 
      - 5432:5432
    # volumes:
    #     - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: root
      POSTGRES_DB: gpt_db 

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    env_file:
      - .env
    image: redis
    restart: always
    ports:
      - 6379:6379

  celery:
      build:
        context: .
        dockerfile: celery.dockerfile
      container_name: celery
      command: celery -A food worker --beat --scheduler django --loglevel=info
      env_file:
        - .env
      depends_on:
        - redis
        - web
        - db

  web:
    build: .
    depends_on:
      - db
      - redis
    env_file:
        - .env
    command: gunicorn food.wsgi:application --bind 0.0.0.0:8000

    ports:
      - 8000:8000
      
# volumes:
#   postgres_data:

