# Generated by Django 4.2.3 on 2023-07-18 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.category'),
        ),
        migrations.AlterField(
            model_name='story',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.category'),
        ),
        migrations.AlterField(
            model_name='story',
            name='tag',
            field=models.ManyToManyField(to='stories.tag'),
        ),
    ]
