# Generated by Django 4.2.3 on 2023-09-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
